### ISSUE TITLE
Overriding or replacing output file

### ISSUE THREAD

**Issue by stupid-kid-af** [stupid-kid-af/Voice-Recorder4Android#1]
#Overriding or replacing output file

Eg : 
Firstly recorded = Bla Bla Blaa..

Out file = testRecordingFile.mp3

Audio = Bla Bla Blaa..

Then Recorded,
I'm Ashutosh..

Out file = testRecordingFile.mp3 (not adding index 1 eg : testRecordingFile1.mp3)

**Comment by ssddOnTop** [comment]
fixed:)

**Comment by ssddOnTop** [comment]
> #Overriding or replacing output file
> 
> Eg :
> Firstly recorded = Bla Bla Blaa..
> 
> Out file = testRecordingFile.mp3
> 
> Audio = Bla Bla Blaa..
> 
> Then Recorded,
> I'm Ashutosh..
> 
> Out file = testRecordingFile.mp3 (not adding index 1 eg : testRecordingFile1.mp3)

fixed:)

**Comment by stupid-kid-af** [comment]
Thanks, @ssddOnTop for fixing this issue.
